@host=http://localhost:5145
@AccountantId=1

POST {{host}}/Orders
Content-Type: application/json

{
  "orderItemsDtos": [
    {
      "itemId": 1,
      "quantity": 2,
      "price": 10
    }
  ],
  "orderType": "Table",
  "tableId": 1,
  "captainId": 1,
  "totalAmount": 10,
  "createdAt": "2025-12-23T15:37:15.601Z"
}
